* Encoding: UTF-8.
MIXED Power_theta_FCz BY Stage Group Cognitive_load Performance Period WITH Age Sex 
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) 
    SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE) 
  /FIXED=Group Period Group*Period | SSTYPE(3) 
  /METHOD=ML 
  /PRINT=DESCRIPTIVES  SOLUTION 
  /RANDOM=INTERCEPT | SUBJECT(Trial*Participant) COVTYPE(ID) 
  /EMMEANS=TABLES(Group*Period) COMPARE(Group) ADJ(BONFERRONI) .
